### ISSUE TITLE
What can cause a PARSING_ERROR type within the RoutingError

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#118]
I see quite a few cases with a PARSING_ERROR, but have not been able to reproduce it. The documentation only says "Error while parsing route data." But what can be the cause of it? A wrong route handle?

**Comment by datasun** [comment]
Import via route handle would fail with [RoutingError.INVALID_PARAMETER](https://docs.in.here.com/static/88867/904187/html/com/here/sdk/routing/RoutingError.html#INVALID_PARAMETER). If you have a reliable case where this happening, please share. This error should only happen in very rare cases, but we will update the documentation to be clearer about it.

**Comment by datasun** [comment]
@StefanTiess Just to confirm, the parsing error happens only in very rare cases when the backend response cannot be parsed by the HERE SDK. 

It can be fixed by updating your app to use a newer HERE SDK version. However, if you would still get this error, it would be a severe issue you should report to us as a bug with the details how & when it has happened. 

Hope this helps.
