### ISSUE TITLE
Traffic does not appear on the map.

### ISSUE THREAD

**Issue by kleeb** [heremaps/here-sdk-examples#137]
Setting 

`_hereMapController.mapScene.setLayerVisibility(MapSceneLayers.trafficFlow, VisibilityState.visible)`

is not adding any data on the map. Checked on the latest 4.11.2 version navigate edition on sample traffic_app: https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/flutter/traffic_app

trafficIncidents works properly adding black lines (after a fix that arrived within 4.11.2), but trafficFlow is empty.

**Comment by kleeb** [comment]
Small comment - by traffic I mean those green, yellow and red lines - not black which are incidents and they work correct after the 4.11.2 fix.

**Comment by datasun** [comment]
Thanks for raising, we will look into it. We have a related issue on our side, that sometimes the traffic flow lines do not appear at first start.

**Comment by datasun** [comment]
Ok, in fact, the issue is valid due to a license issue. 

@kleeb Please contact https://developer.here.com/help directly and ask for a HERE SDK license update. Your credentials will then be enabled to get traffic flow access. This affects Navigate Edition and Explore Edition. Licensing still works for Explore, when you go to developer.here.com instead of the HERE platform self-serve portal.

Sorry for the inconvenience, we will announce in our release notes when licensing will be back to normal.

**Comment by kleeb** [comment]
Thanks! Would be also great to have some kind of readable exception messages for such cases.

**Comment by datasun** [comment]
Agree, but it would complicate usage of the API if exception handling would be required. In fact, it is just expected to work without errors. :) But there should be an error message in the logs already, if I am not wrong.
