### ISSUE TITLE
Is there any difference in routing engine via mobile Navigate SDK and web API V8?

### ISSUE THREAD

**Issue by vadym1930** [heremaps/here-sdk-examples#164]
Could you please help to clarify the next questions:
1. By creating routes via Navigate SDK and web API V8 do we get the same results assuming all request parameters were the same? E.g. the same origin,  the same destination, the same transport mode etc.
2. Is it correct that behind the scene in Navigate SDK the same routing engine version — V8 is used?
3. Is Navigate SDK engine always legging behind the Web V8 engine?
4. How much does mobile SDK v8 differ from web v8?

Extra info:
SDK version: heresdk-navigate-android-4.12.2.0.9350
Web API reference: https://developer.here.com/documentation/routing-api/api-reference-swagger.html

Thank you

**Comment by datasun** [comment]
Hi @vadym1930, there are three routing engines, the `RoutingEngine` operates only online and it is indeed calculating routes with the v8 HERE backend. If you use the exact same parameters, the results should be similar. Routes may still differ due to the time of calculation. The `OfflineRoutingEngine` operates completely offline without contacting the HERE backend. On top, there are certain features that are not available for v8, for example, the [DynamicRoutingEngine](https://docs.in.here.com/static/99752/992552/html/com/here/sdk/trafficawarenavigation/DynamicRoutingEngine.html).

Question #3 probably means if there is a problem with yet unsupported parameters? Not really, as the `RoutingEngine` allows to use any backend parameter via the `setCustomOption()` feature to set key/value params from routing backend.

Question 4 is easy to answer: Besides using same backends for some features the HERE SDK is built upon a completely different stack to support, for example, offline map data.

Hope this helps ...

**Comment by vadym1930** [comment]
@datasun this helps a lot, thank you
