### ISSUE TITLE
Online Routing Engine ignores Height Restriction Visible on Map

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#196]
On the L 723 (Coordinates: 50.734853, 8.075691) the Restriction Layer on the Map shows a Height Restriction of 2.8 meters. But if a route is calculated with a vehicle exceeding that height (eg with 4 meters of height), the routing engine will ignore the restriction on the map, pass though the restricted street and not even show a notice. As this is also a question of security I wonder how those differences between map and routing engine can occur and how they can be avoided. At least that is the one single thing a truck routing engine needs to provide: to not lead drivers into restricted roads. And at least in this situation it is not due to missing map data.

**Comment by datasun** [comment]
Thanks for raising and the precise description. I have created #15396 for investigation on our end. 

Ideally, such bug reports go directly to our help desk, because issues in this repo are usually only targeting the hosted example apps, so going over help desk is much faster and will help us to aggregate all the necessary info.

Nevertheless, can you add which edition, map version and HERE SDK version you have used? 

Thanks!
