### ISSUE TITLE
Flutter (Explore) SDK: some tiles won't load

### ISSUE THREAD

**Issue by markszente** [heremaps/here-sdk-examples#199]
The Flutter (Explore) SDK won't load certain tiles when programmatically controlling the camera. After zooming out and panning around manually, the tiles do load. However, it doesn't seem to be a transient issue, and it is -- as far as I can see -- limited to certain geographic locations. It is reproducible both on iOS and Android.

One location where I have constantly seen it happening is ` 47.36347, 18.86581`, in central Hungary.

I have prepared [a small repo](https://github.com/markszente/here_explore_sdk_tile_issue) where the issue can be quickly reproduced. Please note you'll need to follow [the docs](https://developer.here.com/documentation/flutter-sdk-explore/4.3.0.0/dev_guide/topics/quick-start.html) to set it up, as the SDK and corresponding keys are not included in the repo.

SDK version: Explore, 4.12.10

I've also posted it on [StackOverflow](https://stackoverflow.com/questions/74545031/here-flutter-explore-sdk-some-tiles-wont-load).

**Comment by datasun** [comment]
Thanks for the detailed report. We will try to reproduce this and track the issue in ticket #15455.

**Comment by limingchina** [comment]
@markszente , with the latest HERESDK 4.13.4, I can't reproduce the issue using the example that you've provided. We recently found one issue which can trigger the tile-not-loading issue. In that case, one starts an animation first, then call the LookAt method to set a location, which cancels the previous animation. 

Could you refine your example app to have all the camera calls? This way, we can see if the issue is the one that we found internally. If it's the same issue, one workaround is that adding a zero altitude to the camera lookat call.
