### ISSUE TITLE
FixedCameraBehavior cameraDistanceInMeters not updated

### ISSUE THREAD

**Issue by zenyagami** [heremaps/here-sdk-examples#204]
I have an issue, I'm using `FixedCameraBehavior` for the navigation "Navigation edition", using something like that

```kotlin
visualNavigator.cameraBehavior = FixedCameraBehavior().apply {
        cameraTiltInDegrees = getCameraTilt()
        cameraDistanceInMeters = if (context.isPortrait()) {
            Timber.v("cameraBehavior isPortrait")
            150.0
        } else {
            Timber.v("cameraBehavior landscape")
            200.0
        }
```
if I rotate the screen and I use `visualNavigator.cameraBehavior=null`  and after some seconds/or any time I set again the `FixedCameraBehavior` with `cameraDistanceInMeters =200.0` it will not work, so the camera view is not updated, however if I restart the app and i keep in landscape the `cameraDistanceInMeters` is correct displayed.

as a note, I already started the navigation  `visualNavigator.route = route`
using latest version `heresdk-navigate-android-4.12.10.0.10251.aar`
is any way to fix this?

**Comment by datasun** [comment]
Hi @zenyagami, your code snippet is setting the distance based on whether the screen is portrait or landscape. To iron out issues, try to hardcode the distance values. It should be possible to update the values at any time. 

**FixedCameraBehavior** uses 150 m, by default. Calling it again with 200 m, should have immediate effect after the next location update, that's why I suspect the code snippet maybe uses the portrait value and does not detect you are in landscape. Could that be? Or the device is not receiving a location update and stays therefore on the last value ...

However, since this is not related to the example apps, we cannot help much here. If you still experience issues with updating the fixed distance through camera behavior, please raise a bug ticket for our HERE support team via: https://developer.here.com/help. Thanks!
