### ISSUE TITLE
Android Navigate SDK: Map Overlay Progress

### ISSUE THREAD

**Issue by fedyshyn-volodymyr** [heremaps/here-sdk-examples#208]
Hey.

During my testing, I found an issue with the map overlay progress. For very long routes, the eat-up route progress visualization displays incorrectly. Progress was ahead or behind the current position. I attach a video and a screenshot that demonstrates the problem more clearly. 

Also, the issue is reproduced when manually updating the map overlay progress (without Visual Navigator).

For testing, I used the [Navigation](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/Navigation) demo project and the last version of Navigate SDK (`heresdk-navigate-android-4.12.11.0.10354`). The release notes for this version state that this issue has been resolved, but unfortunately, it still occurs.

Looking forward to your response and recommendations.

https://user-images.githubusercontent.com/119164546/207030913-b3d31384-1123-47f8-bc37-72e66ac8e694.mp4
![Screenshot_20221209_171659](https://user-images.githubusercontent.com/119164546/207030957-eb75aa11-d7d1-4c38-b2f2-b4c50a4c0c90.png)

**Comment by datasun** [comment]
Hi @fedyshyn-volodymyr, thanks for raising. The ticket on our end is #15682. Meanwhile, do you have the coordinates of the route where you saw this behavior? Does the screen orientation matter? Thanks.

**Comment by fedyshyn-volodymyr** [comment]
Start point: 32.718845, -117.094645 (San Diego)
End Point: 38.531610, -121.517526 (Sacramento)


Screen orientation doesn't matter.

**Comment by romandanylyk** [comment]
Hey @HERE-SDK-Support-Team 
Starting Navigate SDK 4.13.4.0 this issue is gone using `MapProjection.GLOBE`, but it still exists with `MapProjection.WEB_MERCATOR` - so it would be nice to fix it there too.

Reproducing the issue is still the same - you only need a big route (400-500 km). After starting the navigation simulation you will notice the progress is out of sync with the current position indicator. 
Since Mercator Projection distortion is mostly visible on the North and South poles, I would recommend testing it in US or Canadian regions so it would be more visible. 

Having this issue, we were forced to switch back to Globe view until it is resolved.

**Comment by HERE-SDK-Support-Team** [comment]
Thanks, @romandanylyk - the issue has been reopened.

**Comment by HERE-SDK-Support-Team** [comment]
We have fixed this for 4.16.3.

**Comment by romandanylyk** [comment]
Great, will check it out once it is released.
