### ISSUE TITLE
Using here map with Jetpack compose

### ISSUE THREAD

**Issue by Strikelon** [heremaps/here-sdk-examples#212]
Hello! 
Please tell me if there are any examples how to use here maps "Navigation Edition" with jetpack compose?
Will you support jetpack compose in the future versions?
Thank you.

**Comment by datasun** [comment]
Hello @Strikelon, we already _support_ Jetpack Compose. However, since the examples are not UI-heavy, we have no plans to _use_ Jetpack Compose as we focus on (mostly) headless HERE SDK code. Using it should be hazzle-free and it should not require any specific treatment when it comes to the HERE SDK.

If you have spotted any particular issue or an unexpected incompatibility, please leave a comment. Thanks!

**Comment by Strikelon** [comment]
I didn't find composable function MapView or HereMap in your library. I use navigation edition. 
Since which version do you support compose? 

Or you suggest to wrap mapView into AndroidView?

The problem is that MapView requires to call methods onCreate, onPause, onResume, onDestroy, loadScene. 

I can't understand how to use MapView in compose.

**Comment by datasun** [comment]
Thanks, we will check if this is possible. This is probably a feature request. The ticket on our side is #15941.

**Comment by thehrlein** [comment]
Also depend on that feature to use here maps in future
