### ISSUE TITLE
How to know, if map marker was drawn on the map screne

### ISSUE THREAD

**Issue by Strikelon** [heremaps/here-sdk-examples#236]
Hi!

Please advice me any method, how to known if map marker was drawn (added) on the map screne?

Sometimes method "mapScene.addMapMarker()" doesn't work, and I can't find any method of map marker status, if mapscene contains it or no?

I can save onbject of map marker in some variable after I called "mapScene.addMapMarker()", but if "mapScene.addMapMarker()" did't work, I can't detected if the map marker from the variable is on the mapscene right now or not.

Thank you.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @Strikelon, adding a marker should always succeed. Also, there is no API that allows you to check what content is currently visible. What you describe is a bug that should never happen. Since this bug is not directly connected nor reproducible with the hosted example apps in this repo, please [contact us](https://developer.here.com/documentation/flutter-sdk-navigate/dev_guide/topics/key-concepts.html#getting-help-when-bugs-occur ) directly. Thank you!
