### ISSUE TITLE
[Bug] Can't use OfflineMaps 

### ISSUE THREAD

**Issue by shinriyo** [heremaps/here-sdk-examples#267]
I tried the sample of `here-sdk-examples/examples/latest/navigate/ios/OfflineMaps/OfflineMaps`.

It said `Cannot find type 'DownloadRegionsStatusListener'`, `MapDownloader`, `MapUpdater` and so on.

<img width="865" alt="スクリーンショット 2023-09-04 17 12 41" src="https://github.com/heremaps/here-sdk-examples/assets/396927/06a28b25-3456-48df-ad6f-d71713b4dd80">

Why do you use such a half-baked project as a sample?

I actually put heresdk in the project and set as framework setting.

<img width="636" alt="スクリーンショット 2023-09-04 17 13 58" src="https://github.com/heremaps/here-sdk-examples/assets/396927/da20ae48-0bf0-41a3-ad2c-d685e880de21">

**Comment by shinriyo** [comment]
Navigation SDK
https://platform.here.com/portal/sdk

download iOS's HERE SDK Navigate Edition

unzip `heresdk-navigate-ios-4.15.3.0.11553.zip`
and unsiped `heresdk-navigate-ios-4.15.3.0.11553.tar.gz` it can build

**Comment by shinriyo** [comment]
It could build but never download.

I pushed `Regions` but `accrssDenied` happned

![Screen Shot 2023-09-04 at 17 42 39](https://github.com/heremaps/here-sdk-examples/assets/396927/0e5109a3-3b30-4a78-8e9e-b24da4c79c9d)
![Screen Shot 2023-09-04 at 17 42 44](https://github.com/heremaps/here-sdk-examples/assets/396927/844b8850-5e92-4e08-a44e-86377b63a1d5)

**Comment by HERE-SDK-Support-Team** [comment]
Hi @shinriyo, thanks for trying this out. The error message you get is expected. It means that your credentials are invalid - for now, in order to get valid credentials for the _Navigate Edition_, you need to contact us: See this _Get Started_ guide: https://developer.here.com/documentation/ios-sdk-navigate/dev_guide/topics/quick-start.html#get-your-credentials 

We plan to improve the onboarding experience, but for now, this step has to be made. You can freely use the _Explore Edition_, but for Navigate, you need to receive credentials from us. Sorry for the inconvenience.
