### ISSUE TITLE
HERE MAP RENDER ISSUE 

### ISSUE THREAD

**Issue by Jatinderkanwar** [heremaps/here-sdk-examples#321]
ON some of the Android devices map is not able to load its showing as White 

I am getting below error 

hsdk-MapRegionSwitcher - Rescheduling authorization request for map switch as current failed with: Authentication failed

same sdk is working on other devices can you please let me know what s the issue there 

I am using sdk version :4.16.3

**Comment by HERE-SDK-Support-Team** [comment]
Hi @Jatinderkanwar 

in order to look into the details, it's best if you contact our in-house support team via: https://www.here.com/contact?intref=dev_docum

We may need to see the logs and details of your environment and credentials.

For now, it looks like an issue related to credentials. Please check also our troubleshooting section: https://www.here.com/docs/bundle/sdk-for-android-navigate-developer-guide/page/topics/tips-troubleshooting.html

Hope this helps. Thanks.
