### ISSUE TITLE
HERE map polyline disappears on weak devices

### ISSUE THREAD

**Issue by Serggiolysen** [heremaps/here-sdk-examples#323]
On Samsung A01, Samsung Tab 2, the route line disappears at some scales.

The problem appears even on the sample application https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/Navigation.

The bug does not depend on the card's features. Video attached.

Lockito was used as location provider.

VisualNavigator instance works fine. Tested on my own app. The same problem occured.

Navigate SDK ver.  4.18, 17.2-17.5      On SDK 4.13 & 4.17.0 that featute works flowlesly.

https://github.com/heremaps/here-sdk-examples/assets/42517623/286d3afa-874e-4032-be24-5435e5e3a253

**Comment by Serggiolysen** [comment]
the same behaviour on 17.2-17.5 Navigate SDK ver

**Comment by Serggiolysen** [comment]
the same (similar) trouble with DynamicCameraBehavior - seems it doesnt work  on  SDK ver. 4.18, 17.2-17.5

on  4.17.0 norlam behavior

**Comment by HERE-SDK-Support-Team** [comment]
Hi @Serggiolysen,

such issues have been fixed in recent updates. Can you try our latest version 4.19.5.0 or newer and if the issue persist, please attach he logs to your question. To speed this up, it will help if you directly contact our in-house support team via https://www.here.com/contact?intref=dev_docum

Hope this helps. Thanks!
