### ISSUE TITLE
heremap navigation

### ISSUE THREAD

**Issue by gaurav472** [heremaps/here-sdk-examples#49]
i have implemented here map navigation it showing everything good in simulation but in real its camera angle and notification methods are not called(already  preferred java example)

**Comment by datasun** [comment]
Have you tried the Android Navigation example from this repo? It shows how to receive notifications for simulation and for real GPS sources. Have you debugged and checked that the Navigator is receiving any location updates?

**Comment by gaurav472** [comment]
hello i am getting the location updates but camera is not moving as per path

**Comment by datasun** [comment]
Hi gaurav472, in order to help, we need a few more information. Otherwise, it will be hard to find out what is going on. Are you using your own code? If that is the case, please try the [Navigation example app](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/Navigation) instead - and see if that works for you. 

Also, where did you get your credentials from? Note, that currently you cannot use the credentials you get from developer.here.com - instead you need to contact HERE.

**Comment by datasun** [comment]
Closing as this seems to be not an issue with the code hosted here. Please comment, if more help is needed. Thanks.
