### ISSUE TITLE
[Flutter] Displaying text over Map Markers

### ISSUE THREAD

**Issue by brazc** [heremaps/here-sdk-examples#55]
Hi,
I'm using **HERE SDK (Explore) v4.5.0.0** for **Flutter 1.22.2**.

I am developing an application that displays objects as map markers on the map, as they are different types of object, I am displaying different markers (svgs) based on type.

While all works as intended, I was wondering whether it's possible to display text over the markers without hardcoding them in the SVGs? 

Since I can have multiple objects of the same type with a unique ID, at the same location.  

Going with the current approach I have in mind (that is hardcoding the text), It wouldn't work in the sense if we have to add more objects. As each marker would need a specific svg.

If this feature is not available yet, it would be nice to have it.
----------------
On another note: Can we expect 'FlyToCoordinate' on the camera anytime soon? LookAtPoint works, but feels too sudden and seems bad for UX.

**Comment by datasun** [comment]
Hi, thanks for the precise questions. 

There's good news, what you are trying to do is already possible with [WidgetPins](https://developer.here.com/documentation/flutter-sdk-explore/4.5.1.0/api_reference/mapview/WidgetPin-class.html): Instead of a marker which allows only one image asset, with a `WidgetPin` you can add a standard Flutter Widget to the map view. The only trade-off is that this consumes a bit more rendering CPU, but any text-on-marker solution would consume that too. As expected for a widget, you can update the text for it at any time.

'FlyToCoordinates' animations are planned for one of the next releases, but for the upcoming 4.5.2 release we will already add an example app to this repo that shows how a smooth bow-type animation is possible using Flutter's Tween class.

Hope this helps.
